## Basic Configuration

baseurl = "https://www.benstenhaug.com" 
builddrafts = false
canonifyurls = false
languageCode = "en-US"

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

author = "Ben Stenhaug"
title = "Ben Stenhaug"

theme = "hugo-goa"

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

## Hugo Built-in Features
# disqusShortname = "https-shenoybr-github-io-hugo-goa-demo" # Comment out to disable Disqus.
googleAnalytics = "XYZ"
enableRobotsTXT = true

## Site Settings
[params]
author = "Ben Stenhaug"
intro = "<a href=\"https://sdsi.stanford.edu//\">Data Science Scholar</a> and PhD student at Stanford."
description = "Previously at <a href=\"https://dssg.uchicago.edu/\">Data Science for Social Good</a>, Khan Academy, and TFA."



authorimage = "ben_stenhaug_profile_pic_square.jpg"
dateformat = "Jan 2, 2006"

## Site Meta Settings
[params.meta]
description = "Ben Stenhaug's personal website"
keywords = "data,datascience,R,tidyverse,stanford,dssg,education,teaching,learning"

## Social Accounts
[params.social]
linkedin = "ben-stenhaug"
github = "stenhaug"
medium = "@benastenhaug"
youtube = "benastenhaug"
email = "benastenhaug@gmail.com"
university = "benastenhaug"
# twitter = "BenStenhaug"

## Extras
[params.extra]
copyright = "© 2018. Ben Stenhaug." 
poweredby = true
highlightjs = true
rss = true

## Main Menu
[[menu.main]]
    name = "posts"
    weight = 100
    identifier = "posts"
    url = "/posts/"
[[menu.main]]
    name = "projects"
    identifier = "projects"
    weight = 200
    url = "/projects/"
#[[menu.main]]
    #name = "tags"
    #identifier = "tags"
    #weight = 550
    #url = "/tags/"
[[menu.main]]
    name = "about"
    identifier = "about"
    weight = 300
    url = "/about/"